mysql:
  url: jdbc:mysql://localhost:3306/sys?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: root

eureka:
  instance: eurekacenter.apps.pas.cloud.dhc.com.cn
  port: 8011
