mysql:
  url: jdbc:mysql://172.16.65.5:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: C890408j

eureka:
  instance: eurekacenter.apps.pas.cloud.dhc.com.cn
  port: 8011
